Calendar Styling + New Datepicker (Sprint004)
whatwedo/CoreBundle pull request #19
Opened 2023-03-22 08:01 UTC by marcwieland95

- Styling Fullcalendar (#47)
- Besserer Datepicker wählen (#35)

2023-03-22 17:51 UTC, tuxes3 requested changes

2023-03-22 17:51 UTC, tuxes3 commented on src/Resources/assets/controllers/datetime_controller.js
> +                'https://cdn.jsdelivr.net/npm/@easepick/bundle@1.2.1/dist/index.css',
keine cdns verwenden. Das css ist ja im gleichen Paket, das soll lokal zur Verfügung gestellt werden.

2023-03-22 17:51 UTC, tuxes3 commented on src/Resources/assets/controllers/datetime_controller.js
> +            lang: 'de-DE',
mach das am besten gerade mit einer Stimulus Value: https://stimulus.hotwired.dev/reference/values

Falls nicht Existential kannst default `de-DE` nehmen.

2023-03-22 17:51 UTC, tuxes3 commented on src/Resources/assets/styles/_tailwind.scss
> +        // @apply px-4 py-2 border border-transparent shadow-sm text-base font-medium rounded-md text-white bg-white hover:bg-neutral-200 focus:ring-primary-500 transition-colors #{!important};
kein auskommentierter code. (Ausser mit Begründung, diese muss auch im Kommentar sein.)

2023-03-23 06:47 UTC, marcwieland95 commented on src/Resources/assets/controllers/datetime_controller.js
> +                'https://cdn.jsdelivr.net/npm/@easepick/bundle@1.2.1/dist/index.css',
Macht Sinn. Wird wohl auch eine Guideline sein für ein Symfony Bundle

2023-03-23 21:52 UTC, tuxes3 approved these changes

2023-03-23 21:52 UTC, merged